OBJS   = tilemap.o
TARGET = tilemaptest
CFLAGS = `pkg-config sdl2 --cflags` -DCRUSTY_TEST -Wall -Wextra -ggdb -Og
LDFLAGS = `pkg-config sdl2 --libs`

$(TARGET): $(OBJS)
	$(CC) $(LDFLAGS) -o $(TARGET) $(OBJS)

all: $(TARGET)

clean:
	rm -f $(TARGET) $(OBJS)

.PHONY: clean
